language: go
install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.40.3/hugo_0.40.3_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - git clone https://github.com/linyows/hugo-theme-flag themes/flag
script:
  - hugo -t flag
after_success:
  - rm -rf public/posts.html
deploy:
  provider: s3
  access_key_id: $S3_KEY
  secret_access_key: $S3_SECRET
  bucket: $S3_BUCKET
  acl: public_read
  region: ap-northeast-1
  local_dir: public
  skip_cleanup: true
  on:
    branch: master
notifications:
  slack: linyows:2oeZ2qcLnaMjbnEYodwEXKTr
  email: false
